-- MySQL Script generated by MySQL Workbench
-- Wed Oct 16 17:09:12 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ubereats
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ubereats
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ubereats` DEFAULT CHARACTER SET utf8 ;
USE `ubereats` ;

-- -----------------------------------------------------
-- Table `ubereats`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ubereats`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) NULL DEFAULT NULL,
  `last_name` VARCHAR(255) NULL DEFAULT NULL,
  `gender` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `phone_number` VARCHAR(255) NULL DEFAULT NULL,
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `role` VARCHAR(255) NULL DEFAULT NULL,
  `is_enable` TINYINT(1) NOT NULL DEFAULT 1,
  `activation_token` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  `active` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `phone_number_UNIQUE` (`phone_number` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ubereats`.`restaurants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ubereats`.`restaurants` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL,
  `is_merchant` TINYINT NULL DEFAULT 0,
  `deliveries_time` TIME NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `preparation_time` TIME NULL DEFAULT NULL,
  `shipping_fee` DOUBLE NULL DEFAULT NULL,
  `user_id` INT(11) NOT NULL,
  `active` TINYINT(1) NULL,
  `is_open` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_restaurants_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_restaurants_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ubereats`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ubereats`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ubereats`.`categories` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `type` ENUM('items', 'supplements') NULL DEFAULT NULL,
  `restaurant_id` INT(11) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `restaurant_id`),
  INDEX `fk_categories_restaurants1_idx` (`restaurant_id` ASC),
  CONSTRAINT `fk_categories_restaurants1`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `ubereats`.`restaurants` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ubereats`.`cuisines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ubereats`.`cuisines` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ubereats`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ubereats`.`orders` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(255) NULL,
  `comment` TEXT NULL DEFAULT NULL,
  `coupon_data` VARCHAR(255) NULL DEFAULT NULL,
  `status` ENUM('pending', 'canceled', 'confirmed', 'ready', 'in_shipment', 'shipped') NULL DEFAULT 'pending',
  `user_id` INT(11) NOT NULL,
  `restaurant_id` INT(11) NOT NULL,
  `ready_at` TIME NULL DEFAULT NULL,
  `delay_added` TIME NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `number_UNIQUE` (`number` ASC),
  INDEX `fk_orders_users1_idx` (`user_id` ASC),
  INDEX `fk_orders_restaurants1_idx` (`restaurant_id` ASC),
  CONSTRAINT `fk_order_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ubereats`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_restaurants1`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `ubereats`.`restaurants` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ubereats`.`shippings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ubereats`.`shippings` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `fee` DOUBLE NULL DEFAULT NULL,
  `user_id` INT(11) NULL DEFAULT NULL,
  `order_id` INT(11) NOT NULL,
  `status` ENUM('pending', 'canceled', 'planned', 'in_progress', 'done') NULL,
  `shipped_at` DATETIME NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `planned_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_shippings_user1_idx` (`user_id` ASC),
  INDEX `fk_shippings_order1_idx` (`order_id` ASC),
  CONSTRAINT `fk_shippings_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ubereats`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shippings_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `ubereats`.`orders` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ubereats`.`menus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ubereats`.`menus` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `restaurant_id` INT(11) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_menus_restaurants1_idx` (`restaurant_id` ASC),
  CONSTRAINT `fk_menus_restaurants1`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `ubereats`.`restaurants` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ubereats`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ubereats`.`items` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `price` DOUBLE NOT NULL DEFAULT 0,
  `old_price` DOUBLE NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `is_available` TINYINT(1) NULL DEFAULT NULL,
  `cuisine_id` INT(11) NULL DEFAULT NULL,
  `restaurant_id` INT(11) NULL DEFAULT NULL,
  `category_id` INT(11) NULL DEFAULT NULL,
  `menu_id` INT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_item_restaurant_idx` (`restaurant_id` ASC),
  INDEX `fk_item_category1_idx` (`category_id` ASC),
  INDEX `fk_items_cuisine1_idx` (`cuisine_id` ASC),
  INDEX `fk_items_menus1_idx` (`menu_id` ASC),
  CONSTRAINT `fk_items_cuisine1`
    FOREIGN KEY (`cuisine_id`)
    REFERENCES `ubereats`.`cuisines` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `ubereats`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_restaurant`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `ubereats`.`restaurants` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_items_menus1`
    FOREIGN KEY (`menu_id`)
    REFERENCES `ubereats`.`menus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ubereats`.`meta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ubereats`.`meta` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(255) NULL DEFAULT NULL,
  `value` VARCHAR(255) NULL DEFAULT NULL,
  `user_id` INT(11) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_meta_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_meta_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ubereats`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ubereats`.`notations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ubereats`.`notations` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `model_type` VARCHAR(255) NOT NULL,
  `model_id` INT NOT NULL,
  `comment` VARCHAR(255) NULL DEFAULT NULL,
  `star` INT(11) NULL DEFAULT NULL,
  `like` TINYINT(1) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_notations_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_notations_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ubereats`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ubereats`.`order_lines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ubereats`.`order_lines` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `quantity` INT(11) NOT NULL,
  `order_id` INT(11) NOT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  `model_id` INT NOT NULL,
  `model_type` VARCHAR(255) NOT NULL,
  `model_price` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_line_order1_idx` (`order_id` ASC),
  CONSTRAINT `fk_order_line_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `ubereats`.`orders` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ubereats`.`days`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ubereats`.`days` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ubereats`.`programmes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ubereats`.`programmes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `day_id` INT NOT NULL,
  `restaurant_id` INT(11) NOT NULL,
  `open_time` TIME NULL DEFAULT NULL,
  `close_time` TIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_programmes_restaurants1_idx` (`restaurant_id` ASC),
  INDEX `fk_programmes_days1_idx` (`day_id` ASC),
  CONSTRAINT `fk_programmes_restaurants1`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `ubereats`.`restaurants` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_programmes_days1`
    FOREIGN KEY (`day_id`)
    REFERENCES `ubereats`.`days` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ubereats`.`restaurants_has_cuisines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ubereats`.`restaurants_has_cuisines` (
  `restaurant_id` INT(11) NOT NULL,
  `cuisine_id` INT(11) NOT NULL,
  PRIMARY KEY (`restaurant_id`, `cuisine_id`),
  INDEX `fk_restaurants_has_cuisines_cuisines1_idx` (`cuisine_id` ASC),
  INDEX `fk_restaurants_has_cuisines_restaurants1_idx` (`restaurant_id` ASC),
  CONSTRAINT `fk_restaurants_has_cuisines_restaurants1`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `ubereats`.`restaurants` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_restaurants_has_cuisines_cuisines1`
    FOREIGN KEY (`cuisine_id`)
    REFERENCES `ubereats`.`cuisines` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ubereats`.`supplements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ubereats`.`supplements` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `price` DOUBLE NOT NULL DEFAULT 0,
  `category_id` INT(11) NULL DEFAULT NULL,
  `restaurant_id` INT(11) NULL DEFAULT NULL,
  `is_available` TINYINT(1) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_supplements_categories1_idx` (`category_id` ASC),
  CONSTRAINT `fk_supplements_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `ubereats`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ubereats`.`items_has_supplements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ubereats`.`items_has_supplements` (
  `item_id` INT(11) NOT NULL,
  `supplement_id` INT NOT NULL,
  PRIMARY KEY (`item_id`, `supplement_id`),
  INDEX `fk_items_has_supplements_items1_idx` (`item_id` ASC),
  INDEX `fk_items_has_supplements_supplements1_idx` (`supplement_id` ASC),
  CONSTRAINT `fk_items_has_supplements_items1`
    FOREIGN KEY (`item_id`)
    REFERENCES `ubereats`.`items` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_items_has_supplements_supplements1`
    FOREIGN KEY (`supplement_id`)
    REFERENCES `ubereats`.`supplements` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ubereats`.`invoices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ubereats`.`invoices` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(255) NULL,
  `status` ENUM('paid', 'unpaid') NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `order_id` INT(11) NOT NULL,
  `total` DOUBLE NULL,
  `issue_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `due_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_invoices_orders1_idx` (`order_id` ASC),
  CONSTRAINT `fk_invoices_orders1`
    FOREIGN KEY (`order_id`)
    REFERENCES `ubereats`.`orders` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ubereats`.`obligatory_supplements_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ubereats`.`obligatory_supplements_categories` (
  `item_id` INT(11) NOT NULL,
  `category_id` INT(11) NOT NULL,
  PRIMARY KEY (`item_id`, `category_id`),
  INDEX `fk_obligatory_supplements_categories_categories1_idx` (`category_id` ASC),
  INDEX `fk_obligatory_supplements_categories_items1_idx` (`item_id` ASC),
  CONSTRAINT `fk_obligatory_supplements_categories_items1`
    FOREIGN KEY (`item_id`)
    REFERENCES `ubereats`.`items` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_obligatory_supplements_categories_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `ubereats`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ubereats`.`criteria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ubereats`.`criteria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ubereats`.`notations_has_criteria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ubereats`.`notations_has_criteria` (
  `notation_id` INT(11) NOT NULL AUTO_INCREMENT,
  `criteria_id` INT(11) NOT NULL,
  PRIMARY KEY (`notation_id`, `criteria_id`),
  INDEX `fk_notations_has_criteria_criteria1_idx` (`criteria_id` ASC),
  INDEX `fk_notations_has_criteria_notations1_idx` (`notation_id` ASC),
  CONSTRAINT `fk_notations_has_criteria_notations1`
    FOREIGN KEY (`notation_id`)
    REFERENCES `ubereats`.`notations` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notations_has_criteria_criteria1`
    FOREIGN KEY (`criteria_id`)
    REFERENCES `ubereats`.`criteria` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ubereats`.`settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ubereats`.`settings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(255) NOT NULL,
  `value` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ubereats`.`onesignals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ubereats`.`onesignals` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `player_id` VARCHAR(255) NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_onesignals_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_onesignals_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ubereats`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ubereats`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ubereats`.`addresses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `addressable_id` INT NULL,
  `addressable_type` VARCHAR(255) NULL,
  `gmap_address` TEXT NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ubereats`.` shippings_recipients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ubereats`.` shippings_recipients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `phone_number` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `shipping_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ shippings_recipients_shippings1_idx` (`shipping_id` ASC),
  CONSTRAINT `fk_ shippings_recipients_shippings1`
    FOREIGN KEY (`shipping_id`)
    REFERENCES `ubereats`.`shippings` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ubereats`.`payment_methods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ubereats`.`payment_methods` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `code` VARCHAR(255) NULL,
  `description` VARCHAR(255) NULL,
  `active` TINYINT(1) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ubereats`.`payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ubereats`.`payments` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `payment_id` VARCHAR(255) NULL DEFAULT NULL,
  `amount_paid` INT NULL DEFAULT NULL,
  `meta` TEXT NULL DEFAULT NULL,
  `status` ENUM('deposit', 'undeposit') NOT NULL,
  `invoice_id` INT NOT NULL,
  `payment_method_id` INT NOT NULL,
  PRIMARY KEY (`id`, `invoice_id`, `payment_method_id`),
  INDEX `fk_payments_invoices1_idx` (`invoice_id` ASC),
  INDEX `fk_payments_payment_method1_idx` (`payment_method_id` ASC),
  CONSTRAINT `fk_payments_invoices1`
    FOREIGN KEY (`invoice_id`)
    REFERENCES `ubereats`.`invoices` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payments_payment_method1`
    FOREIGN KEY (`payment_method_id`)
    REFERENCES `ubereats`.`payment_methods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ubereats`.`wallets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ubereats`.`wallets` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `balance` BIGINT NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_wallets_users1_idx` (`user_id` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  CONSTRAINT `fk_wallets_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ubereats`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ubereats`.`wallet_transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ubereats`.`wallet_transactions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `wallet_id` INT UNSIGNED NOT NULL,
  `amount` BIGINT NULL,
  `hash` VARCHAR(255) NULL,
  `type` ENUM("deposit", "withdraw") NULL,
  `accepted` TINYINT NULL DEFAULT 1,
  `meta` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_transactions_wallets1_idx` (`wallet_id` ASC),
  CONSTRAINT `fk_transactions_wallets1`
    FOREIGN KEY (`wallet_id`)
    REFERENCES `ubereats`.`wallets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ubereats`.`trackings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ubereats`.`trackings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `longitude` DOUBLE NULL,
  `latitude` DOUBLE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_trackings_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_trackings_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ubereats`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ubereats`.`order_status_histories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ubereats`.`order_status_histories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT(11) NOT NULL,
  `status` ENUM('pending', 'canceled', 'confirmed', 'ready', 'in_shipment', 'shipped') NOT NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_order_status_histories_orders1_idx` (`order_id` ASC),
  CONSTRAINT `fk_order_status_histories_orders1`
    FOREIGN KEY (`order_id`)
    REFERENCES `ubereats`.`orders` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
